### PR TITLE
Add bg 

### LINKED ISSUE #5: [feature] Add background image

### PR DESCRIPTION
**Pull request by mmdbalkhi**
#7

### CODE REVIEW

**Comment by Rajkumar-stackcoder** [comment]
@mmdbalkhi can you  pls resolve the conflicts  and then make pr

**Comment by mmdbalkhi** [comment]
> @mmdbalkhi can you pls resolve the conflicts and then make pr

Ok np Just please guarantee do not commit before my pr :))

**Comment by Rajkumar-justcoder** [comment]
> 
> 
> > @mmdbalkhi can you pls resolve the conflicts and then make pr
> 
> Ok np Just please guarantee do not commit before my pr :))

okay np
But just updated the readme so pls see that...

**Comment by mmdbalkhi** [comment]
Hello resolved again. But if the background color was transparent, maybe it would be better. If you want to change the photo, I found this photo from Google and it may not be appropriate.

**Comment by Rajkumar-justcoder** [comment]
> 
> 
> Hello resolved again. But if the background color was transparent, maybe it would be better. If you want to change the photo, I found this photo from Google and it may not be appropriate.

Hi @mmdbalkhi  the images is not visible so pls do changes 
like make size little bit bigger and make changes according to your view

**Comment by mmdbalkhi** [comment]
> > Hello resolved again. But if the background color was transparent, maybe it would be better. If you want to change the photo, I found this photo from Google and it may not be appropriate.
> 
> Hi @mmdbalkhi the images is not visible so pls do changes like make size little bit bigger and make changes according to your view

Hello, please resize the window. This problem is due to the small size of the window

**Comment by Rajkumar-justcoder** [comment]
> 
> 
> > > Hello resolved again. But if the background color was transparent, maybe it would be better. If you want to change the photo, I found this photo from Google and it may not be appropriate.
> > 
> > 
> > Hi @mmdbalkhi the images is not visible so pls do changes like make size little bit bigger and make changes according to your view
> 
> Hello, please resize the window. This problem is due to the small size of the window

yea know that but just remove backgroud color

**Comment by mmdbalkhi** [comment]
> > > > Hello resolved again. But if the background color was transparent, maybe it would be better. If you want to change the photo, I found this photo from Google and it may not be appropriate.
> > > 
> > > 
> > > Hi @mmdbalkhi the images is not visible so pls do changes like make size little bit bigger and make changes according to your view
> > 
> > 
> > Hello, please resize the window. This problem is due to the small size of the window
> 
> yea know that but just remove backgroud color

If you wanted to remove the background color, why did you create the theme? And this was not included in the issue

**Review by Rajkumar-justcoder — CHANGES_REQUESTED** [review]
- Pls make changes discribe below close this per and make new pr 
Change add image according to the size of timer
And add that in theme like user can select it from that
Eg : I want theme of image then user can select image opt from theme menu

**Comment by mmdbalkhi** [comment]
That is, the user gives the photo path?

**Comment by Rajkumar-justcoder** [comment]
> That is, the user gives the photo path?

That would be great if it possible
Other wise static will be fine
Up to your choice @mmdbalkhi

**Comment by mmdbalkhi** [comment]
Ok. I do it. But unfortunately I have a busy and may be a bit late. But be sure I'm do it

**Comment by Rajkumar-justcoder** [comment]
No problem

**Comment by mmdbalkhi** [comment]
Excuse me, is it possible for you to send a suitable png photo (here)?
And that I only change the image and the size of the page because the above issue has nothing to do with the issue(#7).

**Comment by mmdbalkhi** [comment]
Sorry unfortunately I try and it seems tk does not support :(

**Comment by Rajkumar-justcoder** [comment]
> Sorry unfortunately I try and it seems tk does not support :(

Okay np
And  I will review it tomorrow and merge

**Pull request merged**
